image: node:latest

stages:
  - modules
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: modules
  script:
    - npm install

builds:
  image: electronuserland/builder:wine
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*.exe
  script: 
    - npm run dist
